name: Build

on:
  workflow_call:
    inputs:
      mode:
        required: true
        type: string
        default: snapshot
        description: |
          the mode to use. either `snapshot` or `release`. Will affect effective version, as well
          as target-oci-registry.

jobs:
  prepare:
    uses: gardener/cc-utils/.github/workflows/prepare.yaml@master
    with:
      mode: ${{ inputs.mode }}
      version-commit-callback-action-path:
    permissions:
      contents: read

  tests:
    runs-on: ${{ github.repository_owner == 'gardener' && 'ubuntu-latest-large' || 'ubuntu-latest' }}
    steps:
      - uses: gardener/cc-utils/.github/actions/trusted-checkout@master
      - uses: gardener/cc-utils/.github/actions/setup-git-identity@master
      - uses: actions/setup-go@v6
        with:
          go-version: '1.25'
      - name: run-verify
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p /tmp/blobs.d
          make verify-extended |& tee /tmp/blobs.d/verify-log.txt
          tar czf /tmp/blobs.d/gosec-report.tar.gz gosec-report.sarif
          tar czf /tmp/blobs.d/verify-log.tar.gz -C /tmp/blobs.d verify-log.txt
      - name: add-tests-report-to-component-descriptor
        uses: gardener/cc-utils/.github/actions/export-ocm-fragments@master
        with:
          blobs-directory: /tmp/blobs.d
          ocm-resources: |
            - name: gosec-report
              relation: local
              access:
                type: localBlob
                localReference: gosec-report.tar.gz
              labels:
              - name: gardener.cloud/purposes
                value:
                - lint
                - sast
                - gosec
              - name: gardener.cloud/comment
                value: |
                  we use gosec (linter) for SAST scans
                  see: https://github.com/securego/gosec
            - name: test-results
              relation: local
              access:
                type: localBlob
                localReference: verify-log.tar.gz
              labels:
              - name: gardener.cloud/purposes
                value:
                - test


  gardener-landscape-kit:
    permissions:
      contents: read
    needs:
      - tests
      - sast-lint
    strategy:
      matrix:
        args:
          - os: linux
            arch: amd64
            runner: ubuntu-latest
          - os: darwin
            arch: amd64
            runner: ubuntu-latest
          - os: windows
            arch: amd64
            runner: ubuntu-latest
    runs-on: ${{ matrix.args.runner }}
    steps:
      - uses: gardener/cc-utils/.github/actions/trusted-checkout@master
      - uses: actions/setup-go@v6
        with:
          go-version: '1.25'
      - name: build-gardener-landscape-kit
        shell: bash
        run: |
          set -euo pipefail

          os=${{ matrix.args.os }}
          arch=${{ matrix.args.arch }}

          if [ ${os} == 'windows' ]; then
            exe_suffix='.exe'
            archive_suffix='.zip'
          else
            exe_suffix=''
            archive_suffix='.tar.gz'
          fi

          mkdir -p /tmp/blobs.d
          prefix=/tmp/blobs.d/gardener-landscape-kit
          platform_suffix="-${os}-${arch}"
          outpath="${prefix}${platform_suffix}${exe_suffix}${archive_suffix}"
          archive="${prefix}${platform_suffix}.archive"

          GOOS=${os} \
          GOARCH=${arch} \
          BUILD_PACKAGES=./cmd/gardener-landscape-kit \
          BUILD_OUTPUT_FILE=${outpath} \
            make build

          echo "built into ${outpath}"

          if ${{ matrix.args.os == 'windows' }}; then
            (
              cd $(dirname ${outpath})
              zip -j ${archive} $(basename ${outpath})
            )
          else
            tar cvzf ${archive} -C/tmp/blobs.d $(basename ${outpath})
          fi

          unlink ${outpath}
      - uses: gardener/cc-utils/.github/actions/export-ocm-fragments@master
        with:
          blobs-directory: /tmp/blobs.d
          ocm-resources: |
            name: gardener-landscape-kit
            relation: local
            type: executable
            extraIdentity:
              os: ${{ matrix.args.os }}
              architecture: ${{ matrix.args.arch }}
            access:
              type: localBlob
              localReference: >-
                gardener-landscape-kit-${{ matrix.args.os }}-${{ matrix.args.arch }}.archive
